import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("login", "routes/login.tsx"),
  route("logout", "routes/logout.tsx"),
  route("pending", "routes/pending.tsx"),
  route("accept-invite", "routes/accept-invite.tsx"),
  route("auth/google/callback", "routes/auth.google.callback.tsx"),
  route("api/places/search", "routes/api.places.search.tsx"),
  route("api/places/details", "routes/api.places.details.tsx"),
  route("api/polls", "routes/api.polls.tsx"),
  route("dashboard", "routes/dashboard.tsx", [
    index("routes/dashboard._index.tsx"),
    route("about", "routes/dashboard.about.tsx"),
    route("events", "routes/dashboard.events.tsx"),
    route("rsvp", "routes/dashboard.rsvp.tsx"),
    route("restaurants", "routes/dashboard.restaurants.tsx"),
    route("polls", "routes/dashboard.polls.tsx"),
    route("members", "routes/dashboard.members.tsx"),
    route("profile", "routes/dashboard.profile.tsx"),
    route("preview-minimal", "routes/dashboard.preview-minimal.tsx"),
    route("preview-editorial", "routes/dashboard.preview-editorial.tsx"),
    route("preview-product", "routes/dashboard.preview-product.tsx"),
    route("admin", "routes/dashboard.admin._index.tsx"),
    route("admin/events", "routes/dashboard.admin.events.tsx"),
    route("admin/members", "routes/dashboard.admin.members.tsx"),
    route("admin/polls", "routes/dashboard.admin.polls.tsx"),
    route("admin/content", "routes/dashboard.admin.content.tsx"),
    route("admin/email-templates", "routes/dashboard.admin.email-templates.tsx"),
    route("admin/analytics", "routes/dashboard.admin.analytics.tsx"),
    route("admin/backfill-hours", "routes/dashboard.admin.backfill-hours.tsx"),
  ]),
] satisfies RouteConfig;
